### ISSUE TITLE
@react-spring/konva: ` Type instantiation is excessively deep and possibly infinite.` on TypeScript 4.5

### ISSUE THREAD

**Issue by kizahasi** [pmndrs/react-spring#1784]
## 🐛 Bug Report

Components in @react-spring/konva give `TS2589: Type instantiation is excessively deep and possibly infinite.` error on TypeScript 4.5.

It works fine on TypeScript v4.4.4.

## To Reproduce

TypeScript v4.5.3

```typescript
import { animated } from "@react-spring/konva";
import * as ReactKonva from "react-konva";

export default function App() {
  return (
    <ReactKonva.Stage>
      <ReactKonva.Layer>
        <animated.Rect />
      </ReactKonva.Layer>
    </ReactKonva.Stage>
  );
}
```

When I run `tsc`, it gives the following error:

```
src/App.tsx:8:9 - error TS2589: Type instantiation is excessively deep and possibly infinite.

8   <animated.Rect />;
    ~~~~~~~~~~~~~~~~~


Found 1 error.
```

It seems other components in `@react-spring/konva` such as `animated.Text` and `animated.Line` give the same error.

## Expected behavior

No error

## Link to repro (highly encouraged)

<https://github.com/kizahasi/react-spring-konva-ts2589>

and run `yarn run build`

## Environment

- `react-spring` v9.3.2 (`@react-spring/konva` v9.3.1)
- `react` v17.0.2
- `react-konva` v17.0.2-5
- `typescript` v4.5.3

**Comment by joshuaellis** [comment]
This is a typescript problem, not a `@react-spring` issue, as evident by the issue appearing with a change in TS version. 

There's another issue open similar that we're tracking that sort of thing – #1515 

So let's close this in the interest of only having one issue regarding this.

**Comment by miker2049** [comment]
Sorry to bump but does anyone know what the precise culprit is for Konva specifically with this error?  I understand its an issue in #1515 because of something happening between styled-components and three.js, but I am not using styled-components in my project and get this everywhere with Konva components.
