### ISSUE TITLE
`useChain` no longer works in `v9.0.0`

### ISSUE THREAD

**Issue by JakeElder** [pmndrs/react-spring#1367]
## 🐛 Bug Report

`useChain` no longer works as documented in `9.0.0`

## To Reproduce

Take the example from the exisiting documentation, update `react-spring` dependency to `9.0.0`. The error is `Cannot read property 'css' of undefined`

Example sandbox: 
https://codesandbox.io/s/sharp-smoke-2npqw?file=/src/index.js

## Expected behavior

To act as before, waiting for one transition to finish before beginning the next
As in this sandbox: https://codesandbox.io/embed/2v716k56pr

## Link to repro (highly encouraged)

The same sandbox, with only the `react-spring` dep updated from `8.x.x` to `9.0.0`
https://codesandbox.io/s/sharp-smoke-2npqw?file=/src/index.js

I have made a simplified version which gives the error `ref.add is not a function` here:
https://codesandbox.io/s/floral-cloud-nqyj0?file=/src/index.js

## Environment

- `react-spring` v9.0.0
- `react` v16.8.x (or `react-native` v0.58.x)

## Notes

I have read the [breaking changes](https://aleclarson.github.io/react-spring/v9/breaking-changes/) and can't see anything that suggests this wouldn't work.

I'm not sure if I'm missing something, are the [docs on the website](https://www.react-spring.io/docs) current? Is there a WIP version that I should be referring to?

I can try to help with documentation updates if someone with experience with the codebase could identify what api changes have caused the incompatibility and if there is a suggested new way to achieve the same effect.

**Comment by JakeElder** [comment]
As pointed out by @cbmcruz in [this disccussion](https://github.com/pmndrs/react-spring/discussions/1365), it is possible to get the example working in`9.0.0-rc.3` - https://codesandbox.io/s/sandbox-for-react-spring-usechain-900-rc3-gihbn

**Comment by mattfrancis888** [comment]
If it further helps the discussion, the **ref** used for useChain seems to be undefined at useEffect(). As shown here:

https://codesandbox.io/s/elegant-mountain-shy0e

Hence we can't use chains / do:
```
useEffect(() => {
  ref.current.start()
})
```
As documented here: https://aleclarson.github.io/react-spring/v9/breaking-changes/#The-ref-prop

**Comment by cbmcruz** [comment]
For v9 you have to use `useSpringRef` for the ref of a `useSpring` and `ref.start()` inside the `useEffect`

There is some more info [here](https://github.com/pmndrs/react-spring/pull/1134#issue-479878348)

And here is a working example

https://codesandbox.io/s/working-usespring-example-ekl93

**Comment by JakeElder** [comment]
It looks like this overlaps with https://github.com/pmndrs/react-spring/issues/756 - which is a confirmed bug and has more information. @joshuaellis - feel free to close this

**Comment by joshuaellis** [comment]
Thanks, @JakeElder!

**Comment by joshuaellis** [comment]
I'm actually looking at this right now.... so yeah, this issue is actually more helpful the other issue was using a far too old version of `spring`

**Comment by joshuaellis** [comment]
So to build on @cbmcruz's workaround (which was correct and very helpful to me, so thanks). We had a small recursion problem which has a fixed pushed in #1386. Here's a code snippet in the meantime:

```ts
export default function App() {
  const [open, set] = useState(false)

  const springApi = useSpringRef()
  const { size, ...rest } = useSpring({
    ref: springApi,
    config: config.stiff,
    from: { size: '20%', background: 'hotpink' },
    to: {
      size: open ? '100%' : '20%',
      background: open ? 'white' : 'hotpink',
    },
  })

  // notice we're using useSpringRef, not React's useRef
  const transApi = useSpringRef()
  const transition = useTransition(open ? data : [], {
    ref: transApi,
    trail: 400 / data.length,
    from: { opacity: 0, scale: 0 },
    enter: { opacity: 1, scale: 1 },
    leave: { opacity: 0, scale: 0 },
  })

  // This will orchestrate the two animations above, comment the last arg and it creates a sequence
  useChain(open ? [springApi, transApi] : [transApi, springApi], [
    0,
    open ? 0.1 : 0.6,
  ])

  return (
    <div className={styles.wrapper}>
      <animated.div
        style={{ ...rest, width: size, height: size }}
        className={styles.container}
        onClick={() => set(open => !open)}>
        {transition((style, item) => (
          <animated.div
            className={styles.item}
            style={{ ...style, background: item.css }}
          />
        ))}
      </animated.div>
    </div>
  )
}
```

**Comment by Elir-Mahad** [comment]
> As pointed out by @cbmcruz in #1365, it is possible to get the example working in`9.0.0-rc.3` - https://codesandbox.io/s/sandbox-for-react-spring-usechain-900-rc3-gihbn

For anyone looking for an updated version of the codesandbox example shared by @JakeElder ...
Here you go -> https://codesandbox.io/s/e99i2
This example is using react-spring version 9.1.0 (which is the latest version i think ).
Thanks for everyone who helped out with this issue.

**Comment by joshuaellis** [comment]
To add to this we have lots of examples in the demo folder of this repo.

**Comment by arteforme** [comment]
I'm running into an issue where if a `duration` is specified in a `config` for an animation hook that is supplied to `useChain`, any hooks defined after it will not wait for the duration to elapse.  Instead, they'll run soon after the hook, w/ the `duration` specified, starts.

Below are code sandboxes (forked from [original](https://codesandbox.io/embed/2v716k56pr)) that show it working in v8 and not working in v9

* v8 [code sandbox](https://codesandbox.io/s/happy-feynman-s9beo?file=/package.json)  where hooks are running in sequence (expected)
* v9 [code sandbox](https://codesandbox.io/s/peaceful-germain-u322l?file=/src/index.js) where hooks are running sequentially without waiting for the previous hook to finish. (bug)

Please let me know if I can provide any other information or if there is something that I missed in the v9 version.

**Comment by jacinyan** [comment]
> 

Hi, @cbmcruz , thanks for your solutions.
Just curious tho, regarding `useChain`, well, probably along with the `useSpring` signature with dependencies, why would there be very little detail in the docs?
