### ISSUE TITLE
@react-spring/core or @react-spring/three production errors

### ISSUE THREAD

**Issue by kennetpostigo** [pmndrs/react-spring#1078]
## 🐛 Bug Report
Hi, i'm using these to animate R3F components, but I do not run into this in development. The issue only occurs in production:
```js
Uncaught TypeError: r.willAdvance is not a function
    at 9cfe2b4608e7231bacc0d7d7deffe07ef300d220.20fefe92f1d342a18960.js:1
    at Module.d (9cfe2b4608e7231bacc0d7d7deffe07ef300d220.20fefe92f1d342a18960.js:1)
    at a.b.advance (9cfe2b4608e7231bacc0d7d7deffe07ef300d220.20fefe92f1d342a18960.js:1)
    at 9cfe2b4608e7231bacc0d7d7deffe07ef300d220.20fefe92f1d342a18960.js:1
    at 28ddf37e733bed61e8c6ac53a0464422aa01203b.0544bc5f695fe9930e09.js:1
    at Array.forEach (<anonymous>)
    at xe (28ddf37e733bed61e8c6ac53a0464422aa01203b.0544bc5f695fe9930e09.js:1)
```

## To Reproduce:
Here is the code example i'm trying to run, and again, I want to stress this only happens in production
```js
import React, { useRef } from 'react';
import { Canvas, useFrame } from 'react-three-fiber';
import { useSpring } from '@react-spring/core';
import { a } from '@react-spring/three';
import styled from '@emotion/styled';

const endless = true;

const Cube = () => {
  const m: any = useRef();
  useFrame(() => {
    m.current.rotation.y += 0.01;
  });

  const { scale, color } = useSpring({
    from: { scale: [1, 1, 1], color: '#17bebb' },
    to: async next => {
      while (endless) {
        await next({ scale: [4, 4, 4], color: '#FAD8D6' });
        await next({ scale: [1, 1, 1], color: '#17bebb' });
        await next({ scale: [3, 3, 3], color: '#CD5334' });
        await next({ scale: [2, 2, 2], color: '#EDB88B' });
        await next({ scale: [1, 1, 1], color: '##17bebb' });
      }
    }
  });

  return (
    <a.mesh ref={m} scale={scale}>
      <boxBufferGeometry attach="geometry" args={[1, 1, 1]} />
      <a.meshStandardMaterial attach="material" color={color} />
    </a.mesh>
  );
};

const AnimatingWithReactSpring = () => {
  return (
    <Container>
      <Canvas>
        <ambientLight position={[1, 1, 1]} />
        <Cube />
      </Canvas>
    </Container>
  );
};

const Container = styled.div`
  border: 1px solid #ccc;
  border-radius: 5px;
`;
```

## Expected behavior
I expect it to run well, just like it does in development

## Environment
- "@react-spring/core": "^9.0.0-rc.3"
- "@react-spring/three": "^9.0.0-rc.3"

**Comment by aleclarson** [comment]
Please provide a git repository that reproduces the issue. Thanks 👍

**Comment by kennetpostigo** [comment]
The entirety of the code is in that snippet. You need to run it in with an application set to production mode. Also it seems like this is not the first time it has occured as a similar production issue if mentioned here #1069 

I think I've provided enough information. If you want to chase it down feel free, if not thats fine too. @aleclarson

**Comment by aleclarson** [comment]
#1069 is related to Gatsby. Are you using that? If not, could you provide the webpack config that reproduces the issue? Thanks 👍

**Comment by kennetpostigo** [comment]
I'm not using Gatsby. I've come across this using nextjs

**Comment by aleclarson** [comment]
That's good to know! 😆 

Can you share your `next.config.js`?

**Comment by kennetpostigo** [comment]
Heres the config, in case you're wondering what  the transpile plugin below is for, it's that those modules depend on threejs `jsm` code that isn't compiled.

```js
// next.config.js
const withPlugins = require('next-compose-plugins');
const withTM = require('next-transpile-modules')([
  'drei',
  'three',
  'postprocessing'
]);
const refract = require('refractor');
const images = require('remark-images');
const prism = require('@mapbox/rehype-prism');

const styledHighlight = {
  'styled-template-string': {
    pattern: /(styled(\.\w+|\([^\)]*\))(\.\w+(\([^\)]*\))*)*|css|injectGlobal|createGlobalStyle|keyframes|\.extend|\.withComponent)`(?:\$\{[^}]+\}|\\\\|\\?[^\\])*?`/,
    lookbehind: true,
    greedy: true,
    inside: {
      interpolation: {
        pattern: /\$\{[^}]+\}/,
        inside: {
          'interpolation-punctuation': {
            pattern: /^\$\{|\}$/,
            alias: 'punctuation'
          },
          rest: refract.languages.jsx
        }
      },
      string: {
        pattern: /[^$;]+/,
        inside: refract.languages.css,
        alias: 'language-css'
      }
    }
  }
};
refract.languages.insertBefore('jsx', 'template-string', styledHighlight);
refract.languages.insertBefore('js', 'template-string', styledHighlight);

const withMDX = require('@next/mdx')({
  extension: /\.mdx?$/,
  options: {
    remarkPlugins: [images],
    rehypePlugins: [prism]
  }
});

module.exports = withPlugins([withMDX, withTM], {
  pageExtensions: ['ts', 'tsx', 'md', 'mdx']
});

```

**Comment by kennetpostigo** [comment]
Btw, the error doesn't cause the page to break or anything. Just makes my R3F components that depend on react-spring animation not render. All other R3F components work like normal

**Comment by ahtcx** [comment]
I also get this when bundling with `webpack@5.0.0-beta.22`. I didn't have enough time to dig further in to the issue and reverted to `webpack@4.43.0` which works fine, but it seems to be around how webpack was importing modules.

**Comment by aleclarson** [comment]
> reverted to `webpack@4.43.0` which works fine

Interestingly, that's the version of webpack that `next` is using:
https://github.com/vercel/next.js/blob/681ebfa5cbe24b738ee08a4a5964c0b942af49bb/packages/next/package.json#L110

**Comment by ivnaleta** [comment]
> Please provide a git repository that reproduces the issue. Thanks
Hi.
It can be reproduced on example from react-three-fiber docs:
https://codesandbox.io/s/r3f-react-spring-basic-demo-sm41y
It runs fine in codesandbox and in dev mode (if run by `npm start`), but  animation not working with same error in build version (`npm run build`)

**Comment by ivnaleta** [comment]
Also there is a very similar error when build with typescript.
Code like 
```
import {a} from "react-spring/three";
console.log('a', a);
```
work fine in dev, but build app not starting due to error:
``` globals.ts:16 Uncaught TypeError: a.a is not a constructor
    at Module.<anonymous> (globals.ts:16)
    at i ((index):1)
    at Object.<anonymous> (FrameLoop.ts:2)
    at Object.<anonymous> (2.829ff874.chunk.js:2)
    at i ((index):1)
    at Object.<anonymous> (2.829ff874.chunk.js:2)
    at i ((index):1)
    at Object.<anonymous> (three.js:1)
    at i ((index):1)
    at Module.54 (main.cf74ec6e.chunk.js:1)
``` 

Which  is apparently line ```export let frameLoop = new FrameLoop()```.


Here repository with this error - https://github.com/ivnaleta/ts-three-spring-build-error

**Comment by aleclarson** [comment]
The issue was that `"sideEffects": false` was being used when it shouldn't be, causing `Globals.assign` calls to be tree-shaked. Will be fixed in next RC. 👍

**Comment by ivnaleta** [comment]
> The issue was that `"sideEffects": false` was being used when it shouldn't be, causing `Globals.assign` calls to be tree-shaked. Will be fixed in next RC.


Need some suggestion / some help.
Right now because of combination of problems react-spring + react-three-fiber is unusable for me:
*  9x version dosn't build
* In 8x version infinite loops cause browser freeze because of this issue -  https://github.com/react-spring/react-spring/issues/59
* Don’t want to change webpack config like kennet (using react-cli)

I tried to fork 9x branch, but currently `npm run build` doesn’t work, if I understand correctly this branch is wip. 
Maybe you could point me to a more stable branch / commit of 9x?
Or maybe its just bad idea to use 9x version for production right now and it should be better to use something else? (I take react-spring because of react-three-fiber guide).

**Comment by aleclarson** [comment]
@ivnaleta You could manually remove `"sideEffects": false` from the `package.json` of every `node_modules/@react-spring/*` directory, then use [patch-package](https://github.com/ds300/patch-package) to auto-apply those changes when `node_modules` is re-installed.

Otherwise, if you still want to build v9 locally, you can follow the [Contributing Guide](https://github.com/react-spring/react-spring/blob/v9/CONTRIBUTING.md) and let me know if something trips you up. 👍

**Comment by ivnaleta** [comment]
@aleclarson 
thanks, i ended up with script, but patch-package was very helpful

**Comment by iam4x** [comment]
I can confirm that using NextJS with webpack > ^4.44.x is broken by this, in the mean time you can force webpack to ^4.43.x with resolutions in your package.json:

```
  "resolutions": {
    "webpack": "~4.43.0"
  },
```

**Comment by kennetpostigo** [comment]
I'm not opposed to waiting for a fix in the next version, any idea of when that might be?

**Comment by heymartinadams** [comment]
I can confirm that upgrading from NextJS `9.4.5-canary.45` to `9.5.0` produces the same error for me as well.

**Comment by CharlieHess** [comment]
I'm hitting this in a similar environment (Next + r3f + react-spring) and none of the workarounds listed here work.

⛔ `patch-package` to remove `sideEffects` for all spring packages
⛔ `webpack@4.4.3`
⛔  `next@9.4.5-canary.43`

**Comment by Emiliano-Bucci** [comment]
Same for me here. Is there any quick fix? All the available "solutions" didn't work for me :/

**Comment by Emiliano-Bucci** [comment]
Is there a way to use patch-package? Because it seems that it doesn't patch the changes that are only applied to the `package.json` :/

**Comment by ivnaleta** [comment]
@CharlieHess @Emiliano-Bucci 
I ended up adding scpipt below in package.json postinstall hook. 


```
const replace = require('replace-in-file');

const removeAllSideEffectsFalseFromReactSpringPackages = async () => {
  try {
    const results = await replace({
      files: "node_modules/@react-spring/*/package.json",
      from: `"sideEffects": false`,
      to: `"sideEffects": true`
    });

  // console.log(results); // uncomment to log changed files
  } catch (e) {
    console.log('error while trying to remove string "sideEffects:false" from react-spring packages', e);
  }

}


removeAllSideEffectsFalseFromReactSpringPackages();
```

**Comment by ahtcx** [comment]
@ivnaleta you can acheive the same thing with [`patch-package`](https://github.com/ds300/patch-package) as [@aleclarson stated](https://github.com/react-spring/react-spring/issues/1078#issuecomment-664036914) which worked for me and looks a lot cleaner.

**Comment by ivnaleta** [comment]
It is cleaner, but doesn't work for me 
I didn't figure out why, although there is a few open issues in patch-package repo about changing package.json.

**Comment by Emiliano-Bucci** [comment]
@ivnaleta Try adding `--exclude` at the end of the command, it should work. Example: `npx patch-package react-spring --exclude`

**Comment by creativiii** [comment]
Okay so, I tried many of the fixes here, but none of them work. `patch-package`  looked really promising, but trying to run it after making the changes returns:
```
$ npx patch-package
patch-package 6.2.2
Applying patches...

**ERROR** Failed to apply patch for package @react-spring/animated at path
  
    node_modules/@react-spring/animated

  This error was caused because patch-package cannot apply the following patch file:

    patches/@react-spring+animated+9.0.0-rc.3.patch

  Try removing node_modules and trying again. If that doesn't work, maybe there was
  an accidental change made to the patch file? Try recreating it by manually
  editing the appropriate files and running:
  
    patch-package @react-spring/animated
  
  If that doesn't work, then it's a bug in patch-package, so please submit a bug
  report. Thanks!

    https://github.com/ds300/patch-package/issues
```

Has anyone actually been able to fix this? Is there a development branch that we can use in the meantime?

**Comment by anim8rDev** [comment]
I'm running into this same problem too (using Gatsby).   Is there an update to how long it may (or may not) be fixed?   I wasn't able to get patch-package to work (user error, I'm sure).  I resorted to drastic measures by switching to Framer for the animation on all but one page (this last one would be a serious endeavor).  Just wondering if there was any sort of timeline? 

Thanks.

**Comment by mr-wildcard** [comment]
had the exact same error in production build only and using @iam4x solution helped me.

```js
// in package.json

"resolutions": {
  "webpack": "~4.43.0"
},
```

**Comment by marklundin** [comment]
> The issue was that `"sideEffects": false` was being used when it shouldn't be, causing `Globals.assign` calls to be tree-shaked. Will be fixed in next RC. 👍

Thanks for isolating this @aleclarson. Is there any timeline on the next RC?

**Comment by vietnezo** [comment]
> @CharlieHess @Emiliano-Bucci
> I ended up adding scpipt below in package.json postinstall hook. (`"postinstall": "node postinstall.js"`, + "replace-in-file in devDependencies)
> 
> ```
> const replace = require('replace-in-file');
> 
> const removeAllSideEffectsFalseFromReactSpringPackages = async () => {
>   try {
>     const results = await replace({
>       files: "node_modules/@react-spring/*/package.json",
>       from: `"sideEffects": false`,
>       to: `"sideEffects": true`
>     });
> 
>   // console.log(results); // uncomment to log changed files
>   } catch (e) {
>     console.log('error while trying to remove string "sideEffects:false" from react-spring packages', e);
>   }
> 
> }
> 
> 
> removeAllSideEffectsFalseFromReactSpringPackages();
> ```

Thank you, you saved my day!!

I added theses script in my project

```
"scripts": {
    "dev": "node postinstall.js && next dev",
    "build": "node postinstall.js && next build",
    "start": "next start",
},
```

Hope this issuse is fixed in next version!

**Comment by jerelmiller** [comment]
Confirming that removing `"sideEffects": false` from package.json fixed the issue for me. Thanks for the suggestion @aleclarson!

**Comment by adyz** [comment]
Hi!

I had a gatsby project where I used react-spring and I get the same error after updating my dependencies.

**Comment by adyz** [comment]
I had a gatsby project where I used react-spring and I get the same error after updating my dependencies. I've rolled back all the packages along with the package.lock file too.

**Comment by creativiii** [comment]
> I had a gatsby project where I used react-spring and I get the same error after updating my dependencies. I've rolled back all the packages along with the package.lock file too.

This is a known issue, if you scroll up in the thread there's multiple temporary solutions available!

**Comment by skrhlm** [comment]
Could this not be released as a patch ? I think a lot of people are using the rc3 because it has been said that it's more stable than 8.x, and since rc4 seems quite distant it might be a good idea to get really breaking things like this onto npm.

**Comment by brotzky** [comment]
Thank you, @creativiii. Those steps worked perfectly. It's possible patch-package has been updated as I didn't have to do this step:

- Go into each file and delete everything apart from the bit that mentions "sideEffects": false (so that it looks like the example above) 

I only had to run `npx patch-package --exclude 'nothing' @react-spring/<folder>` 

Thanks again for the detailed steps. We really appreciate it.

**Comment by Inviz** [comment]
Seeing the same with preact & create-react-app.

**Comment by bzmillerboy** [comment]
I faced this issue on Gatsby v2.24.91 two hours before go live time, ugh.

Thanks @creativiii, confirmed these steps worked for me.

**Comment by Inviz** [comment]
Also managed to solve it by pinning web pack to 4.4.3

**Comment by svirins** [comment]
> > @CharlieHess @Emiliano-Bucci
> > I ended up adding scpipt below in package.json postinstall hook. (`"postinstall": "node postinstall.js"`, + "replace-in-file in devDependencies)
> > ```
> > const replace = require('replace-in-file');
> > 
> > const removeAllSideEffectsFalseFromReactSpringPackages = async () => {
> >   try {
> >     const results = await replace({
> >       files: "node_modules/@react-spring/*/package.json",
> >       from: `"sideEffects": false`,
> >       to: `"sideEffects": true`
> >     });
> > 
> >   // console.log(results); // uncomment to log changed files
> >   } catch (e) {
> >     console.log('error while trying to remove string "sideEffects:false" from react-spring packages', e);
> >   }
> > 
> > }
> > 
> > 
> > removeAllSideEffectsFalseFromReactSpringPackages();
> > ```
> 
> Thank you, you saved my day!!
> 
> I added theses script in `package.json` and it worked.
> 
> ```json
> "scripts": {
>     "dev": "node postinstall.js && next dev",
>     "build": "node postinstall.js && next build",
>     "start": "next start",
> },
> "dependencies": {
>     "react-spring": "9.0.0-rc.3",
> },
> "devDependencies": {
>     "replace-in-file": "^6.1.0"
> },
> ```
> 
> Hope this issuse would be fixed in next version!

Thank you so much! Definitely, save my day!

**Comment by Apapin** [comment]
Same issue with vanilla create-react-app, yay for prod-only issues 😬 
Fixed with `patch-package` which is a nifty tool to learn about, thanks for the pointer!

**Comment by heyimalex** [comment]
Commands to do @creativiii 's method mentioned [here](https://github.com/pmndrs/react-spring/issues/1078#issuecomment-692000408) apart from setting up `patch-package`.

```bash
find ./node_modules/@react-spring -type f -depth 2 -name package.json -exec sed -i '' '/"sideEffects": false/d' {} +
find ./node_modules/@react-spring -type d -depth 1 | xargs -L1 -I{} basename "{}" | xargs L1 -I{} npx patch-package --exclude 'nothing' "@react-spring/{}"
```

**Comment by jdillick** [comment]
For the record, even with the potential simplicity of using patch-package, this effort is vastly more complex for projects than simply publishing an 9.0.0-rc.4 with this fix. 

patch-package (and a like strategy) suffers from some fragile build context problems. It is easy to enact this, have it work locally, and fail on a remote build system.

Such is the case for my project and building on heroku. Their devDependency phase of build applies this patch correctly, only to reinstall the package again after pruning devDependencies, and this time patch-package fails due to slightly different working directory context.

While this sort of issue isn't really the *fault* of react-spring, it could be totally avoidable (this whole work-around would be as well) with such a low effort action by the maintainer. Please, please with a cherry-on-top,  npm publish 9.0.0-rc.4 with this trivial build fix.

If main branch is in a bad state, you could cut a hotfix branch off tag https://github.com/pmndrs/react-spring/releases/tag/v9.0.0-rc.3, apply fix, bump to v9.0.0-rc.4, and `npm publish` This would be so helpful. 🥺

**Comment by heyimalex** [comment]
@jdillick Made a PR #1229 which should make this easy.

**Comment by chenxsan** [comment]
For people who's using `react-spring` along with webpack, here's a workaround I believe you can use in `webpack.config.js` before a new `react-spring` is out with the fix:

```
  module: {
    rules: [
      {
        test: /react-spring/,
        sideEffects: true
      },
```

**Comment by lukesmurray** [comment]
@heyimalex small typo in your comment. second L1 in the second command is missing a hyphen

> Commands to do @creativiii 's method mentioned [here](https://github.com/pmndrs/react-spring/issues/1078#issuecomment-692000408) apart from setting up `patch-package`.
> 
> ```shell
> find ./node_modules/@react-spring -type f -depth 2 -name package.json -exec sed -i '' '/"sideEffects": false/d' {} +
> find ./node_modules/@react-spring -type d -depth 1 | xargs -L1 -I{} basename "{}" | xargs -L1 -I{} npx patch-package --exclude 'nothing' "@react-spring/{}"
> ```

**Comment by yahia1997ezat** [comment]
Hi, I have a create-react-app, I see you run these commands in the terminal but when I try to run them I got the following warning/error

` find ./node_modules/@react-spring -type d -depth 1 | xargs -L1 -I{} basename "{}" | xargs -L1 -I{} npx patch-package --exclude 'nothing' "@react-spring/{}"`
find: warning: you have specified the -depth option after a non-option argument -type, but options are not positional (-depth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.

find: paths must precede expression: 1
Usage: find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]

**Comment by mknepprath** [comment]
> For people who's using `react-spring` along with webpack, here's a workaround I believe you can use in `webpack.config.js` before a new `react-spring` is out with the fix:
> 
> ```
>   module: {
>     rules: [
>       {
>         test: /react-spring/,
>         sideEffects: true
>       },
> ```

Thanks @chenxsan - that worked for me!

**Comment by enkicoma** [comment]
> > For people who's using `react-spring` along with webpack, here's a workaround I believe you can use in `webpack.config.js` before a new `react-spring` is out with the fix:
> > ```
> >   module: {
> >     rules: [
> >       {
> >         test: /react-spring/,
> >         sideEffects: true
> >       },
> > ```
> 
> Thanks @chenxsan - that worked for me!

Hi @mknepprath @chenxsan 
I am facing the same issue:
```
   "next": "10.0.3",
    "@react-spring/web": "^9.0.0-rc.3",
    "react-three-fiber": "^5.3.10",
```

May I ask to help me to understand regarding `webpack.config.js`
 I thought that webpack it's bounded in Next.js by default? and if I will create that file in root dir it will override the default one? How should look like the `webpack.config.js` ? 

Cheers!

**Comment by mknepprath** [comment]
@enkicoma You'll need to create a next.config.js file as described here: https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config

**Comment by enkicoma** [comment]
> @enkicoma You'll need to create a next.config.js file as described here: https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config

tried many configs and still getting `TypeError: r.willAdvance is not a function`. Does my next config look right to you?

```js 
const withTM = require('next-transpile-modules')
  ([
    '@react-three/drei',
    'three',
    '@react-spring/web',
    'react-three-fiber'
  ])

module.exports = {
  ...withTM(),
  rules: [
    {
      test: /react-spring/,
      sideEffects: true
    }
  ]
}
```

**Comment by enkicoma** [comment]
switched back to     "next": "9.4.4",  and it works with:

```js
const withTM = require('next-transpile-modules')
  ([
    '@react-three/drei',
    'three',
    '@react-spring/web',
    'react-three-fiber'
  ])

module.exports = {
  ...withTM()
  // rules: [
  //   {
  //     test: /react-spring/,
  //     sideEffects: true
  //   }
  // ]
}
```

**Comment by wmcb91** [comment]
@enkicoma I was able to adapt @chenxsan's to work with Next 10.0.3 by adding a webpack config function to my next.config.js file:

```js
module.exports = {
  ...
  webpack: config => {
    config.module.rules.push({
      test: /react-spring/,
      sideEffects: true,
    })

    return config
  },
}
```

This fixed the `TypeError: r.willAdvance is not a function` error on my production build.

**Comment by enkicoma** [comment]
> @enkicoma I was able to adapt @chenxsan's solution to work with Next 10.0.3 by adding a webpack config function to my next.config.js file:
> 
> ```js
> module.exports = {
>   ...
>   webpack: config => {
>     config.module.rules.push({
>       test: /react-spring/,
>       sideEffects: true,
>     })
> 
>     return config
>   },
> }
> ```
> 
> This fixed the `TypeError: r.willAdvance is not a function` error on my production build.

Confirm - it works! I asked for some help on discord and combined 3 things together with your one and finally:
`next.config.js`
```js
const withTM = require('next-transpile-modules')
  ([
    '@react-three/drei',
    'three',
    '@react-spring/web',
    'react-three-fiber'
  ])

module.exports = withTM({
  webpack: config => {
    config.module.rules.push({
      test: /react-spring/,
      sideEffects: true,
    })

    return config
  },
})
```
Thank you for your help and Happy New year!

**Comment by rh389** [comment]
In case it helps anyone else, I wanted as light-touch a solution as possible since (hopefully 🙏 ) we'll get an rc4 soon.

Add a script to your root `package.json`

```json
  "scripts": {
    "react-spring-issue-1078": "find node_modules -path \\*@react-spring/\\*/package.json -exec sed -i.bak 's/\"sideEffects\": false/\"sideEffects\": true/g' {} +",
    "postinstall": "npm run react-spring-issue-1078",
   }
```

(NB: Won't generally work on windows for obvious reasons, but should be mac and linux compatible)

**Comment by Kais3rP** [comment]
Same problem in prod on Heroku, CRA unejected app . spring@9.0.0-rc.3  .

**Comment by mrgoonie** [comment]
> ```js
> config.module.rules.push({
>       test: /react-spring/,
>       sideEffects: true,
>     })
> ```

Confirm that this solution works, nice approach, the code looks much cleaner now 👍

**Comment by carmandale** [comment]
> ```js
> ```js
> config.module.rules.push({
>       test: /react-spring/,
>       sideEffects: true,
>     })
> ```
> 
> 
> 
> Confirm that this solution works, nice approach, the code looks much cleaner now 👍
> ```

I am having this problem as well. Where do I put this code? I am not using Next. Just React and R3F.
thanks,
Dale

**Comment by guirkgumbo** [comment]
> In case it helps anyone else, I wanted as light-touch a solution as possible since (hopefully 🙏 ) we'll get an rc4 soon. Personally I'm using unejected CRA 4, but this should be generic.
> 
> Add a script to your root `package.json`, and run it on `postinstall`:
> 
> ```json
>   "scripts": {
>     "react-spring-issue-1078": "find node_modules -path \\*@react-spring/\\*/package.json -exec sed -i.bak 's/\"sideEffects\": false/\"sideEffects\": true/g' {} +",
>     "postinstall": "npm run react-spring-issue-1078",
>    }
> ```
> 
> (NB: Won't generally work on windows for obvious reasons, but should be mac and linux compatible)

Confirms that this works for those using CRA. many thanks

**Comment by enkicoma** [comment]
> > ```js
> > ```js
> > config.module.rules.push({
> >       test: /react-spring/,
> >       sideEffects: true,
> >     })
> > ```
> > 
> > 
> > Confirm that this solution works, nice approach, the code looks much cleaner now 👍
> 
> I am having this problem as well. Where do I put this code? I am not using Next. Just React and R3F.
> thanks,
> Dale

I have included it in my `next.config.js` but if you are not using next, I have no idea...( sorry )
But @guirkgumbo  approach looks like you can include it in `package.json`

**Comment by carmandale** [comment]
> ```json
> "scripts": {
>     "react-spring-issue-1078": "find node_modules -path \\*@react-spring/\\*/package.json -exec sed -i.bak 's/\"sideEffects\": false/\"sideEffects\": true/g' {} +",
>     "postinstall": "npm run react-spring-issue-1078",
>    }
> ```

I have added this to my package.json file and then created a new build with yarn build. But when I deploy, I still get the same error of FrameLoop.ts:173 Uncaught TypeError: r.willAdvance is not a function

any ideas? 

thanks,
Dale

**Comment by rh389** [comment]
You'd need to run `yarn install` (or directly: `yarn run react-spring-issue-1078`) to make it run and modify the relevant files before running `build`. If you've already done that I'm not sure why it wouldn't work for you - maybe try one of the other webpack config approaches.

**Comment by carmandale** [comment]
thank you! @rh389 . That was it. IT works now.

**Comment by carmandale** [comment]
@rh389 - do I need to run that each time I do a build? or is it one and done?
thanks,
Dale

**Comment by rh389** [comment]
> do I need to run that each time I do a build? or is it one and done?

The command modifies the relevant `package.json` files inside `node_modules`, those changes will persist on disk until `node_modules` is reinstalled, so it doesn't need to run on every build. In fact, from now on it should run automatically at least as often as it needs to, after any install operation ([`postinstall`](https://docs.npmjs.com/cli/v6/using-npm/scripts#npm-install) is a special lifecycle script).

**Comment by jason-roh** [comment]
@carmandale I used your cmd to fix this issue I have been struggling all day. It's fixed after running your cmd. Thank you so much!

> ```json
> ```json
> "scripts": {
>     "react-spring-issue-1078": "find node_modules -path \\*@react-spring/\\*/package.json -exec sed -i.bak 's/\"sideEffects\": false/\"sideEffects\": true/g' {} +",
>     "postinstall": "npm run react-spring-issue-1078",
>    }
> ```
> 
> 
> 
> I have added this to my package.json file and then created a new build with yarn build. But when I deploy, I still get the same error of FrameLoop.ts:173 Uncaught TypeError: r.willAdvance is not a function
> any ideas?
> thanks,
> Dale
> ```

**Comment by matthewkwong2** [comment]
> ```json
> find node_modules -path \\*@react-spring/\\*/package.json -exec sed -i.bak 's/\"sideEffects\": false/\"sideEffects\": true/g' {} +
> ```

And for the Windows platform, this is the PowerShell script to do the same thing.
```powershell
$reactSpringPackageJSONs = Get-ChildItem -Path node_modules\\*@react-spring/\\*/package.json

foreach ($reactSpringPackageJSON in $reactSpringPackageJSONs) {
  (Get-Content $reactSpringPackageJSON) 
    | Foreach-object { $_ -replace '"sideEffects": false', '"sideEffects": true' } 
    | Set-Content $reactSpringPackageJSON
}
```

**Comment by misterrodger** [comment]
This works for me with Next 10 and next-images, variation on the above:

```
const withImages = require("next-images");

module.exports = withImages({
  webpack: (config) => {
    config.module.rules.push({
      test: /react-spring/,
      sideEffects: true,
    });
    return config;
  },
});
```

**Comment by janarosmonaliev** [comment]
This solution worked for me: https://github.com/pmndrs/react-spring/issues/1069#issuecomment-748519455

**Comment by Dnathan33** [comment]
> patch-package
How exactly did you do this?

**Comment by dgsunesen** [comment]
> @CharlieHess @Emiliano-Bucci
> I ended up adding scpipt below in package.json postinstall hook. (`"postinstall": "node postinstall.js"`, + "replace-in-file in devDependencies)
> 
> ```
> const replace = require('replace-in-file');
> 
> const removeAllSideEffectsFalseFromReactSpringPackages = async () => {
>   try {
>     const results = await replace({
>       files: "node_modules/@react-spring/*/package.json",
>       from: `"sideEffects": false`,
>       to: `"sideEffects": true`
>     });
> 
>   // console.log(results); // uncomment to log changed files
>   } catch (e) {
>     console.log('error while trying to remove string "sideEffects:false" from react-spring packages', e);
>   }
> 
> }
> 
> 
> removeAllSideEffectsFalseFromReactSpringPackages();
> ```

Great stuff! Worked! 🎉

**Comment by ricardoham** [comment]
Hello guys this issue reproduced with `"next": "^10.0.7"` and I'm using the **react-spring parallax** module `"@react-spring/parallax": "^9.0.0-rc.3"`

I've tried all of the approaches and the error still reproducing with the app in production(Github pages).

Does anyone know how to avoid this error?

**Comment by matthewkwong2** [comment]
> Hello guys this issue reproduced with the verisons of `"react-spring": "^8.0.27"` `"next": "^10.0.7"` and I'm using the **react-spring parallax** module `"@react-spring/parallax": "^9.0.0-rc.3"`
> 
> I've tried all of the approaches and the error still reproducing with the app in production(Github pages).
> 
> Does anyone know how to avoid this error?

Scroll up!!! A contributor has already explained what's the cause and there are literally a bunch of workarounds available.

**Comment by darkusss** [comment]
Any of the above answers doesn't help out when using docker.
If anyone who found a workaround and it works with docker, PLEASE reply on this comment.

P.S It would be appreciated to see some replies :)

**Comment by heyimalex** [comment]
@darkusss All of the above answers help when using docker. There's nothing special about building in docker.

**Comment by matthewkwong2** [comment]
@darkusss For the workarounds, you can either
1. Edit the webpack config (prefered)
2. Replace the content in `package.json`

I can't see why these workarounds will not work for docker. Can you elaborate?

**Comment by darkusss** [comment]
@heyimalex Yeah, It works locally, but on staging doesn't

**Comment by darkusss** [comment]
@matthewkwong2 
Both of them don't work on staging

**Comment by matthewkwong2** [comment]
You need to provide more information. A simple "not working" doesn't help at all. Can you provide the error message at least?

**Comment by darkusss** [comment]
The error in the console on a page that uses the library was - `Uncaught TypeError: r.willAdvance is not a function`

**Comment by matthewkwong2** [comment]
That means the workaround is not applied. What method do you end up using?

**Comment by darkusss** [comment]
Using next.js I edited webpack config in next.config.js

**Comment by matthewkwong2** [comment]
Give us a look at the content of `next.config.js`.

**Comment by darkusss** [comment]
It looks like:
`
module.exports = {
  webpack: (config) => {
    config.module.rules.push({
      test: /react-spring/,
      sideEffects: true,
    });
    return config;
  },
};`

**Comment by matthewkwong2** [comment]
weird, it should work

**Comment by matthewkwong2** [comment]
RC 3 has been released for months now. Since then, there are quite some commits and updates. Are there any plans to release an RC 4 or even an official release?

**Comment by joshuaellis** [comment]
> RC 3 has been released for months now. Since then, there are quite some commits and updates. Are there any plans to release an RC 4 or even an official release?

Please see #1330

**Comment by joshuaellis** [comment]
@Emiliano-Bucci, the latest version being 9? Can you share a repo, this is odd.

**Comment by Emiliano-Bucci** [comment]
@joshuaellis Yes, version 9 (sorry); i'll create a repo to reproduce asap (sadly it's a private repo the one where I find the issue); I'll let you know :)

**Comment by joshuaellis** [comment]
Thansk @Emiliano-Bucci lets open a new issue too.

**Comment by matthewkwong2** [comment]
> Is there a way to modify this webpack in create-react-app without ejecting?

Have a look at `@craco/craco`.

**Comment by ColinFendrick** [comment]
> > Is there a way to modify this webpack in create-react-app without ejecting?
> 
> Have a look at `@craco/craco`.

That was my thought as well. I tried setting `module.exports = {
  webpack: config => {
    config.module.rules.push({
      test: /react-spring/,
      sideEffects: true,
    });
    return config;
  },
};`

in my craco.config.js but that didn't seem to work. I have never used craco before so I'm not sure it accepts a factory fn instead of a plain object here?
